// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using envtamer.Data;

#nullable disable

namespace envtamer.Migrations
{
    [DbContext(typeof(EnvTamerContext))]
    partial class EnvTamerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("envtamer.Data.EnvVariable", b =>
                {
                    b.Property<string>("Directory")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Directory", "Key");

                    b.ToTable("EnvVariables");
                });
#pragma warning restore 612, 618
        }
    }
}
